module.exports = {
  RECIPES_RECEIVED: "RECIPES_RECEIVED",
  FEATURED_RECIPE_RECEIVED: "FEATURED_RECIPE_RECEIVED",
  RECIPE_BOX_RECEIVED: "RECIPE_BOX_RECEIVED",
  DETAILED_RECIPE_RECEIVED: "DETAILED_RECIPE_RECEIVED"
};
